"use client"

import { useEffect } from "react"

export function PrivacyPolicyIntl() {
  // Set document language for accessibility
  useEffect(() => {
    document.documentElement.lang = "en"
  }, [])

  return (
    <article className="prose prose-slate max-w-none dark:prose-invert prose-headings:font-semibold prose-a:text-primary prose-a:no-underline hover:prose-a:underline">
      <h1>Privacy Policy for SkillMap</h1>

      <p className="text-sm text-muted-foreground">
        Last Updated: January 2025
      </p>

      <p>
        MornScience ("we," "our," or "us") respects your privacy and is committed to protecting the personal information of our users ("User" or "you"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application, SkillMap (the "App").
      </p>

      <p>
        This policy is designed to comply with the General Data Protection Regulation (GDPR) and Google Play Store Developer Policies.
      </p>

      <hr />

      <h2>1. Information We Collect</h2>

      <p>We collect information to provide and improve our educational tools, specifically our AI-powered assessment and quiz generation features.</p>

      <h3>A. Personal Data</h3>
      <p>We collect personally identifiable information that you voluntarily provide to us when registering:</p>
      <ul>
        <li><strong>Account Information:</strong> Email address, username, and login credentials (passwords are stored in encrypted formats).</li>
      </ul>

      <h3>B. User-Generated Content (File Uploads)</h3>
      <p>To utilize the App's core AI features, you may upload documents, text files, or other materials ("User Content").</p>
      <ul>
        <li><strong>Purpose:</strong> We process these files solely to analyze content and generate relevant quiz questions and learning materials for you.</li>
        <li><strong>Privacy:</strong> These files are processed by our AI algorithms and are stored securely. You can delete your uploaded files at any time through the App settings.</li>
      </ul>

      <h3>C. Usage Data & Performance Metrics</h3>
      <p>We automatically collect data regarding your interaction with the App to provide Personalized Assessments:</p>
      <ul>
        <li><strong>Learning Progress:</strong> Quiz scores, time spent on questions, and completion rates.</li>
        <li><strong>Capability Reports:</strong> Data on identified weak areas and strength indicators generated by our algorithms.</li>
        <li><strong>Technical Data:</strong> Device type, operating system, crash logs, and error reporting to ensure App stability.</li>
      </ul>

      <hr />

      <h2>2. How We Use Your Information</h2>

      <p>We use the collected data for the following specific purposes:</p>
      <ul>
        <li><strong>AI Processing & Service Delivery:</strong> To feed uploaded content into our AI algorithms for the purpose of generating educational questions and summaries.</li>
        <li><strong>Personalization:</strong> To analyze your performance data and generate custom capability assessment reports and learning paths.</li>
        <li><strong>Account Management:</strong> To manage your registration and authentication.</li>
        <li><strong>Improvement:</strong> To analyze usage trends and improve the accuracy of our AI algorithms.</li>
      </ul>

      <hr />

      <h2>3. Legal Basis for Processing (GDPR)</h2>

      <p>If you are located in the European Economic Area (EEA), we process your data based on the following legal grounds:</p>
      <ul>
        <li><strong>Consent:</strong> You have given us permission to process your data (e.g., uploading files for analysis).</li>
        <li><strong>Contract:</strong> Processing is necessary to provide the services you requested (e.g., generating a quiz).</li>
        <li><strong>Legitimate Interests:</strong> For improving our App, security, and fraud prevention.</li>
      </ul>

      <hr />

      <h2>4. Data Sharing and Third-Party Services</h2>

      <p>We do not sell your personal data. We may share information with third-party service providers strictly to perform App functions:</p>
      <ul>
        <li><strong>AI Service Providers:</strong> We utilize third-party AI models to process text and generate questions.</li>
        <li><strong>Cloud Storage & Hosting:</strong> We use secure cloud providers to store your account data and learning progress.</li>
        <li><strong>Analytics:</strong> We may use tools to understand user behavior and improve our services.</li>
      </ul>

      <p>These parties are contractually obligated to protect your data and only use it for the services we request.</p>

      <hr />

      <h2>5. Data Retention</h2>

      <p>We retain your personal information only as long as necessary:</p>
      <ul>
        <li><strong>Account Data:</strong> Retained until you delete your account.</li>
        <li><strong>User Content (Files):</strong> Retained in your history until you delete them.</li>
        <li><strong>Performance Data:</strong> Retained to maintain your historical progress reports.</li>
      </ul>

      <hr />

      <h2>6. Your Rights (GDPR & Google Play)</h2>

      <p>Regardless of your location, we grant you the following rights regarding your data:</p>
      <ul>
        <li><strong>Right to Access:</strong> You may request a copy of the personal data we hold about you.</li>
        <li><strong>Right to Correction:</strong> You may request that we correct inaccurate data.</li>
        <li><strong>Right to Deletion (Erasure):</strong> You can request the deletion of your account and all associated data (including uploaded files and quiz history) directly within the App settings or by contacting us.</li>
        <li><strong>Right to Portability:</strong> You may request your data in a structured, commonly used machine-readable format.</li>
        <li><strong>Right to Withdraw Consent:</strong> You may withdraw consent for data processing at any time (this may limit App functionality).</li>
      </ul>

      <p>To exercise these rights, please contact us at the email address provided in Section 10 below.</p>

      <hr />

      <h2>7. Data Security</h2>

      <p>We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. This includes encryption of data in transit (HTTPS) and at rest.</p>

      <hr />

      <h2>8. Children's Privacy</h2>

      <p>SkillMap is not intended for children under the age of 13 (or the relevant age of digital consent in your country). We do not knowingly collect data from children. If we become aware that we have collected such data, we will delete it immediately.</p>

      <hr />

      <h2>9. Changes to This Policy</h2>

      <p>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the "Last Updated" date. Continued use of the App constitutes acceptance of the changes.</p>

      <hr />

      <h2>10. Contact Us</h2>

      <p>If you have questions about this Privacy Policy or our data practices, please contact us:</p>

      <ul>
        <li><strong>Developer:</strong> MornScience</li>
        <li><strong>Email:</strong> support@mornscience.com</li>
      </ul>

      <style jsx>{`
        article {
          font-feature-settings: "liga" 1, "kern" 1;
        }
      `}</style>
    </article>
  )
}
